@startuml "Flujo Detallado del Módulo de Entrega"
left to right direction

skinparam linetype ortho

actor "Operador de entrega" as delivery

rectangle "Módulo de Entrega(ENT)" {
    usecase "CU-ENT-001:\nAutenticar (Credencial)" as CUENT001
    usecase "CU-ENT-002:\nConsultar Pedidos\nen Despache" as CUENT002
    usecase "CU-ENT-003:\nCancelar Pedido" as CUENT003
    usecase "CU-ENT-004:\nGestionar Pago\ny Despacho" as CUENT004
    usecase "CU-ENT-005:\nVerificar QR\ny Confirmar" as CUENT005

    CUENT004 .> CUENT002 : <<extend>>
}

rectangle "Sistemas Externos"{
    actor "Módulo del Cliente" as cliente <<System>>
    actor "Módulo de Cocina (KDS)" as kds <<System>>
    actor "Lector QR (Hardware)" as qr <<System>>
}

delivery -- CUENT001
delivery -- CUENT002
delivery -- CUENT003
delivery -- CUENT004

CUENT003 -- kds
CUENT003 -- cliente

cliente -- CUENT005
QR -- CUENT005
@enduml